{
 "title": "Tracker Stats",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "tracker",
    "label": "Tracker",
    "query": {
     "query": "label_values(tracker_up_status,tracker)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up",
   "type": "stat",
   "description": "Number of trackers reporting metrics successfully",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(tracker_up_status == 1)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Down",
   "type": "stat",
   "description": "Number of trackers failing to report metrics",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(tracker_up_status == 0)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Seeding",
   "type": "stat",
   "description": "Number of seeding torrents",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(tracker_seeding_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Leeching",
   "type": "stat",
   "description": "Number of torrents downloading",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(tracker_leeching_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HnR",
   "type": "stat",
   "description": "Number of Hit and Runs reported",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tracker_hit_and_runs_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "${tracker}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "tracker" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tracker_up_status{tracker=\"${tracker}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tracker_upload_bytes{tracker=\"${tracker}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tracker_download_bytes{tracker=\"${tracker}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tracker_ratio{tracker=\"${tracker}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HnR",
   "type": "stat",
   "description": "Number of Hit and Runs reported",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tracker_hit_and_runs_count{tracker=\"${tracker}\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}